project_id = "ldrhykrcmisnopgoldos"

[functions.generate]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.publish-post]
verify_jwt = false
