// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://ldrhykrcmisnopgoldos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkcmh5a3JjbWlzbm9wZ29sZG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NTQ1MzAsImV4cCI6MjA5MzEzMDUzMH0.j9OtU8GtnTiz1QtZipnbOCT_lf8m7Jw0Kkzi6-GSeWk";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});